[custom-cid-normalization]
exten => s,1,NoOp(--- Tafreshi Iran CID Processing ---)
; فیلتر کردن اعداد
exten => s,n,Set(CALLERID(num)=${FILTER(0-9,${CALLERID(num)})})
; فراخوانی اسکریپت بش با AGI
exten => s,n,AGI(tafreshi_cid_logic.sh,${CALLERID(num)})
exten => s,n,Return()
